### ISSUE TITLE
Add python 32-bit support 

### ISSUE THREAD

**Issue by LexiconCode** [tusharsadhwani/yen#14]
yen allows for neach use case in python distribution. Adding python 32bit support enhances the use case for yen.

**Comment by tusharsadhwani** [comment]
<img width="603" alt="image" src="https://github.com/tusharsadhwani/yen/assets/43412083/6192ec46-0a6f-49e1-bcda-51534acb8ea5">

It's mostly there. Now just need to compile the binary for 32bit as well.

**Comment by LexiconCode** [comment]
Is there a flag to force 32 bit from command line?

**Comment by tusharsadhwani** [comment]
what do you mean? To download 32 bit even on a 64 bit machine?

**Comment by tusharsadhwani** [comment]
New flag, `--32bit` it is.
