### ISSUE TITLE
Windows install.bat overwrites User's PATH

### ISSUE THREAD

**Issue by Gregory-K** [tusharsadhwani/yen#15]
`install.bat` seems to overwrite User's env `PATH` variable with the System-wide PATH (System PATH + User PATH).

The PATH environment variable is constructed from a System part and a User part that are both stored in the registry.

`setx PATH "%PATH%;%yenpath%"` appends `yenpath` to [System PATH + User PATH] and sets it as the User's PATH.

**Comment by Gregory-K** [comment]
I haven't tested it more than twice. I didn't have the time to test it thoroughly. The severity of the issue the first time it occurred prompted me to write those scripts in pull request #16.

Also note that setx truncates the value to 1024 characters, and long PATHs are common in development setups.

**Comment by tusharsadhwani** [comment]
Awesome, let me take a look. I had zero idea about batch files when I made this so it's good to get some input from others.
