### ISSUE TITLE
ability to pass through script arguments?

### ISSUE THREAD

**Issue by stev-0** [tusharsadhwani/yen#32]
When running a python module that as installed as a scipt with `yen run xxx --version` I get the yen help

But when running directly `/~/.yen_packages/venv_xxxx/bin/python -m xxxx --version`
it works as expected

Is there are special syntax for the following arguments? I imagine that the `--` arg is just getting interpreted as arguments to yen.

**Comment by tusharsadhwani** [comment]
`yen run xxx -- --version` should work, can you try that?

**Comment by stev-0** [comment]
Yes, it does, thanks, closing
