### ISSUE TITLE
Portable yen for xonsh shell install case

### ISSUE THREAD

**Issue by anki-code** [tusharsadhwani/yen#33]
Hey! Thank you for sharing this to the world!
In the readme I see:
> Zero dependencies: No need to have Python installed, no need to look into apt, homebrew etc., just run one shell command to get yen set up locally.

I have [xonsh-install](https://github.com/anki-code/xonsh-install) project for awesome [xonsh shell](https://github.com/xonsh/xonsh) where mamba allows to install python and xonsh into isolated directory (e.g. `~/.local/xonsh-env`) and add path to `xonsh-env/bin` to PATH to run xonsh.

Is there a way to do the same with yen? If you can share just the list of the commands it will be awesome!

Thanks!

**Comment by tusharsadhwani** [comment]
So yen itself is a binary file, which you install with a curl command. 

If you want to install other packages the way xonsh installs itself, you can use `yen install`:

`yen install meowsay`

this will put `meowsay` in `~/.yen_packages/meowsay`, and running `yen ensurepath` will put `~/.yen_packages` in `PATH`.

**Comment by tusharsadhwani** [comment]
`YEN_PYTHONS_PATH` is mentioned in the README, but the others aren't, I should add them.

The project is also getting large enough to warrant a readthedocs page I believe. I'll work on it.
