### ISSUE TITLE
Usual "don't modify my shell environment" issue

### ISSUE THREAD

**Issue by pawamoy** [tusharsadhwani/yen#34]
Common request for tools that similarly modify my env files upon installation :slightly_smiling_face:  Could yen by default not modify .bashrc/.zshrc and provide an option to opt-in? Or at least an option to opt-out that is clearly documented right above/under the curl installation line :slightly_smiling_face:

**Comment by tusharsadhwani** [comment]
How about a prompt to ask to modify the file `(y/n)` ?

**Comment by pawamoy** [comment]
That'd be great, yes! I suppose that users automating the installation of yen in CI or other places will want some mechanism to prevent interactivity too? Or there's always `yes n | curl ...` to the rescue.

**Comment by tusharsadhwani** [comment]
yeah `-y` is not that hard to add

`curl ... | bash -y` should be fine i think
