### ISSUE TITLE
avoid hardcoding PYTHON_INSTALLS_PATH 

### ISSUE THREAD

**Issue by woutervh** [tusharsadhwani/yen#6]
I would like to control where PYTHON_INSTALLS_PATH is located 
by setting an environment variable to keep my $HOME clean.

**Comment by tusharsadhwani** [comment]
Sounds good, PRs are welcome.

**Comment by woutervh** [comment]
Please review https://github.com/tusharsadhwani/yen/pull/7/

**Comment by tusharsadhwani** [comment]
v0.3.0 has been released, consider testing it once after using the install script?

**Comment by woutervh** [comment]
Tested succesfully.
